services:
  linkedin-bot:
    build: .
    container_name: linkedin-bot
    volumes:
      - ./resources:/code/resources
      - ./screenshots:/code/screenshots
    env_file:
      - .env # Load environment variables from .env file
    networks:
      - ljpa-network
  selenium:
    image: selenium/standalone-chromium # VNC-enabled
    ports:
      - "4444:4444" # Selenium WebDriver
      - "${NOVNC_PORT:-7900}:7900" # VNC port (connect with VNC viewer)
    shm_size: '2g' # Critical for Chrome
    depends_on:
      - linkedin-bot
    networks:
      - ljpa-network
    environment:
      - SE_VNC_NO_PASSWORD=1 # Optional: Disable VNC password
  g4f:
    image: hlohaus789/g4f:latest-slim
    container_name: g4f
    volumes:
      - ./har_and_cookies:/app/har_and_cookies
      - ./generated_images:/app/generated_images
    environment:
      - G4F_DEBUG=true
    command: >
      sh -c "rm -rf /app/g4f/ &&
             pip install -U g4f[slim] &&
             python -m g4f --debug"
    networks:
      - ljpa-network
    depends_on:
      - linkedin-bot
    restart: unless-stopped

networks:
  ljpa-network:
    driver: bridge
