services:
  selenium:
    image: selenium/standalone-chromium
    container_name: selenium-container
    ports:
      - "4444:4444"
      - "${NOVNC_PORT:-7900}:7900"
    shm_size: '2g'
    networks:
      - ljpa-network
    environment:
      - SE_VNC_NO_PASSWORD=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 1s
      timeout: 3s
      retries: 30

  g4f:
    image: hlohaus789/g4f:latest-slim
    container_name: g4f-container
    volumes:
      - ./har_and_cookies:/app/har_and_cookies
      - ./generated_images:/app/generated_images
    environment:
      - G4F_DEBUG=true
    ports:
      - "1337:1337"
    networks:
      - ljpa-network
    command: >
      sh -c "rm -rf /app/g4f/ &&
             pip install -U g4f[slim] &&
             python -m g4f --debug"
    restart: unless-stopped

  linkedin-bot:
    build: .
    container_name: linkedin-bot
    volumes:
      - ./resources:/code/resources
      - ./screenshots:/code/screenshots
    env_file:
      - .env
    networks:
      - ljpa-network

networks:
  ljpa-network:
    driver: bridge